#!/bin/ruby

require 'autotest/timestamp'
require 'autotest/restart'
require 'autotest/growl'
require 'autotest/fsevent'

Autotest.add_hook(:initialize) {|at|
  %w{.git ._* vendor tmp log doc}.each do |ex|
    at.add_exception ex
  end
}


